### ISSUE TITLE
Does not open vim 

### ISSUE THREAD

**Issue by CodisRedding** [domenic/opener#10]
The browser and tabs open just fine. The issue is with apps, they don't open. You can see that I want vim to open at the root of the path in the config, but it opens in Finder instead. I was originally using `open` for this, but it wasn't working when I supplied `vim` as the preferred app to open the fine, so I tried opener instead.

Any suggestions would be great.
## config

``` json
{
  "browser": [
  ],
  "apps": [
    "vim /Users/rocky/Src/pastoral-acts/."
  ]
}
```
## script

``` node
var open = require('open');
var opener = require('opener');
var Config = require('./config/config.json');
var sleep = require('sleep');
var _ = require('lodash');

function _run(sources) {
  _.forEach(sources, function(source) {
    opener(source);
    sleep.sleep(1);
  });
}

/**
 * Browser Tabs
 */
_run(Config.browser);

/**
 * Applications
 */
_run(Config.apps);
```

**Comment by tgfjt** [comment]
@fourq 

FYI: with my mac, `opener -a macvim ./test.txt`

**Comment by MichaelDimmitt** [comment]
if you want to open vim here is the path on a mac 😜
`open /usr/bin/vim`

**Comment by CodisRedding** [comment]
hehe, this was from 2014. I don't remember a thing about it. Thanks for the tip! =)
