### ISSUE TITLE
Encodes url?

### ISSUE THREAD

**Issue by voronianski** [domenic/opener#14]
I'm using opener with `#` in url 

```js
var text = 'Goo some';
var url = 'https://www.google.com/#q=' + text;
opener(url);
```

and it gets encoded in browser (chrome):

```
https://www.google.com/%23q=Goo%20some
```

**Comment by domenic** [comment]
Hmm. Can you find any command line invocation that causes Chrome to open to the correct URL? I.e. one you can just run in your shell?

**Comment by voronianski** [comment]
@domenic it's my fault - I need to do `encodeURIComponent(text)` before.
