### ISSUE TITLE
Error: Command failed: open npm run build

### ISSUE THREAD

**Issue by katopz** [domenic/opener#15]
Hi,

Is that `opener npm run build` suppose to work? When I try `opener npm run build` I got
```shell
> opener npm run build

/usr/local/lib/node_modules/opener/opener.js:57
            throw error;
            ^

Error: Command failed: open npm run build
```
BTW, I try to open new terminal for db server and another one for local server.

Thanks

**Comment by jakub-g** [comment]
@katopz why would you like to run `opener npm` instead of just directly `npm`? (i see it's listed in README but I don't see a use case:))

**Comment by gristel** [comment]
Do you have a build script that npm can run?

**Comment by domenic** [comment]
Closing due to lack of answer to the question at https://github.com/domenic/opener/issues/15#issuecomment-215378971
