### ISSUE TITLE
unref() doesn't seem to work

### ISSUE THREAD

**Issue by Sidewinder1138** [domenic/opener#16]
Opener is working great for launching my browser from my node script. But the problem I'm having is that if I kill node (via ctrl-c in the console), then my browser goes down with it! (In this case firefox on linux). I tried calling unref() like in your example but it doesn't seem to help, firefox just dies along with node.

I'm assuming that I'm doing something dumb, but could really use help figuring this out. Seems that everyone would want the child process to stay running, maybe that should be the default behavior?

**Comment by Sidewinder1138** [comment]
OK I realize now that unref() only helps with the event loop. What I want is to set the "detached" option on the child process, so that even if Node goes down, the child (in my case firefox) stays up.

**Comment by jakub-g** [comment]
Hello @Sidewinder1138 

FYI I had this kind of issue with my module (biased-opener, which used to use opener, but since I switched to browser-launcher) and I solved it with:

```
                if (instance) {
                    instance.process.stdin.unref();
                    instance.stdout.unref();
                    instance.stderr.unref();
                    instance.process.unref();
                }
```

https://github.com/jakub-g/biased-opener/blob/master/index.js#L78-L83

Hope that helps

**Comment by domenic** [comment]
This seems pretty well-documented in the readme ("Plus, it returns the child process created, so you can do things like let your script exit while the window stays open:")
