### ISSUE TITLE
Is that possible to get information form the tabs opened with opener?

### ISSUE THREAD

**Issue by shouwei** [domenic/opener#25]
Hi Guys, 

I have a program which has to construct an HTTP URL based on user's input and open the URL in an individual chrome tab. So this packet really does me a big favor.
For the next step, I want to extract some information from the opened tables, such as download link, email, and so on. Does this module also provide this kind of features? Or any other candidate solutions are welcome. 

Thank you for your reading.

**Comment by domenic** [comment]
Nope, it just opens things.
