### ISSUE TITLE
Mac: command line arguments for apps, not supported.

### ISSUE THREAD

**Issue by MichaelDimmitt** [domenic/opener#26]
an application that uses a bash script and takes command line arguments using $1.

## works in terminal 
```open Installer.app --args parameter```

## does not work in opener
```opener (path.join(access_screen_saver, "Installer.app --args MarineAquarium3.2"));```

## look at the second answer for more clarification. 
https://superuser.com/questions/16750/how-can-i-run-an-application-with-command-line-arguments-in-mac-os

**Comment by domenic** [comment]
"Does not work in opener" is not valid JavaScript code nor terminal code, so let me close this.

**Comment by domenic** [comment]
(That is, you're supposed to use an array for command-line arguments:

```js
opener([path.join(access_screen_saver, "Installer.app"), "--args", "MarineAquarium3.2");
```

**Comment by MichaelDimmitt** [comment]
@domenic, thank you. I will try that method.
