### ISSUE TITLE
Support opening browser in private mode?

### ISSUE THREAD

**Issue by pke** [domenic/opener#27]
Would that be possible to run the system browser in private mode in a new window?

**Comment by domenic** [comment]
No idea; sounds like something individual browsers might expose as command-line flags or similar. Probably best to consult their documentation.

**Comment by pke** [comment]
Solved it already by defining a task: 

`open-chrome": "opener chrome --new-window --incognito --auto-open-devtools-for-tabs"`

and can be used by tasks:

`start: open-chrome -- http://localhost:1234 && webpack-dev-server`
