### ISSUE TITLE
No Typescript Support

### ISSUE THREAD

**Issue by johnnyshankman** [domenic/opener#40]
Would be great if this export came with `.d.ts` types so that it can be used in a TS environment without overrides or external installs.
![Screenshot_2024-04-15_at_1_54_18 PM](https://github.com/domenic/opener/assets/6632701/a661162d-19cf-442c-adf6-a20aa0757ddf)

https://www.npmjs.com/package/@types/opener

**Comment by domenic** [comment]
I'm not interested in TypeScript for this repository. I hear there is some other repository where you can add types for JavaScript packages; I suggest you look into that solution.
