### ISSUE TITLE
Query params in http link on Windows

### ISSUE THREAD

**Issue by 3y3** [domenic/opener#9]
```
http://www.example.com?param1=1&param2=2
```
opens as 
```
http://www.example.com?param1=1
```
because `&` symbol parses as command separator.
Correct link:
```
http://www.example.com?param1=1^&param2=2
```

Is this expected behavior?

**Comment by michaeldrotar** [comment]
I ran into this as well and tried to double quote the url, but got an error that windows couldn't find /http://myurl... not sure why it had a slash in front. I found that exec seems to work with a quoted url though on Windows.

    .exec('cmd /c start "" "'+url+'"')

**Comment by domenic** [comment]
That makes me think `opener('"http://www.example.com?param1=1^&param2=2"')` will work (i.e. actually include the double quotes). I'd be open to auto-escaping *but* currently we support multiple arguments (I'm not sure why) which makes it kind of tricky...
